# generated by datamodel-codegen:
#   filename:  prusa_openapi.yaml
#   timestamp: 2026-05-03T18:01:49+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field, RootModel


class Capabilities(BaseModel):
    upload_by_put: bool | None = Field(
        False,
        alias='upload-by-put',
        description='The printer supports uploading GCodes by the PUT method (as\ndescribed in this document). It is capable of doing the PUT and\nHEAD to /api/v1/files/{storage}/{path} and it is capable of\nanswering the /api/v1/storage endpoint.\n\nIn absence of this capability, client MAY opt to try the legacy\n"octoprint" POST to /api/files/{storage}.\n',
    )


class Version(BaseModel):
    api: str = Field(..., examples=['1.0.0'])
    version: str = Field(..., examples=['0.7.0'])
    printer: str = Field(..., examples=['1.3.1'])
    text: str = Field(..., examples=['PrusaLink 0.7.0'])
    firmware: str = Field(..., examples=['3.10.1-4697'])
    sdk: str | None = Field(None, examples=['0.7.0'])
    capabilities: Capabilities | None = Field(
        {},
        description="Additional capabilities the printer has. The object is expected to\nbe extended in the future with more capabilities. The absence of a\ncapability in the object, or the complete absence of the object\nmeans the printer doesn't support such capability (probably doesn't\neven know such capability might exist).\n",
        validate_default=True,
    )


class Type(Enum):
    LOCAL = 'LOCAL'
    SDCARD = 'SDCARD'
    USB = 'USB'


class Storage(BaseModel):
    name: str | None = Field(
        None,
        description='Name of the storage, based on selected language',
        examples=['PrusaLink gcodes'],
    )
    type: Type = Field(..., description='Storage source')
    path: str = Field(
        ..., description='Path to storage (not display path)', examples=['/local']
    )
    print_files: int | None = Field(
        None, description='Size of all print files in bytes', examples=[19216842]
    )
    system_files: int | None = Field(
        None, description='Size of all system files in bytes', examples=[4242]
    )
    free_space: int | None = Field(
        None, description='System free space in bytes', examples=[1921681142]
    )
    total_space: int | None = Field(
        None, description='System total space in bytes', examples=[8589934592]
    )
    available: bool = Field(
        ..., description='Whether the storage is available or not', examples=[True]
    )
    read_only: bool | None = Field(
        None, description='Whether the storage is read only', examples=[False]
    )


class Config(BaseModel):
    path: str | None = Field(None, examples=['/dev/video0'])
    name: str | None = Field(None, examples=['Camera L4D'])
    driver: str | None = Field(None, examples=['V4L2'])
    resolution: str | None = Field(None, examples=['1280x720'])


class Camera(BaseModel):
    camera_id: str | None = Field(None, examples=['sh42arta'])
    config: Config | None = None
    connected: bool | None = Field(
        None, description='Camera is successfully connected to PrusaLink'
    )
    detected: bool | None = Field(
        None, description='Camera is detected by PrusaLink, but not saved yet'
    )
    stored: bool | None = Field(
        None, description='Camera configuration is saved in PrusaLink'
    )
    linked: bool | None = Field(None, description='Camera is linked to PrusaConnect')


class TriggerScheme(Enum):
    TEN_SEC = 'TEN_SEC'
    THIRTY_SEC = 'THIRTY_SEC'
    SIXTY_SEC = 'SIXTY_SEC'
    EACH_LAYER = 'EACH_LAYER'
    FIFTH_LAYER = 'FIFTH_LAYER'
    MANUAL = 'MANUAL'


class AvailableResolution(BaseModel):
    width: int | None = Field(None, examples=[640])
    height: int | None = Field(None, examples=[480])


class Resolution(BaseModel):
    width: int | None = Field(None, examples=[640])
    height: int | None = Field(None, examples=[480])


class Capability(Enum):
    TRIGGER_SCHEME = 'TRIGGER_SCHEME'
    IMAGING = 'IMAGING'
    RESOLUTION = 'RESOLUTION'
    ROTATION = 'ROTATION'
    EXPOSURE = 'EXPOSURE'
    FOCUS = 'FOCUS'


class CameraConfig(BaseModel):
    name: str | None = Field(
        None, description='Name of the camera', examples=['MuadDib_Camera_1']
    )
    trigger_scheme: TriggerScheme | None = Field(
        None, description='When the snapshot is taken'
    )
    available_resolutions: list[AvailableResolution] | None = None
    resolution: Resolution | None = None
    focus: float | None = Field(
        None, description='Focus of the camera (0.0 - 1.0)', examples=[0.5]
    )
    capabilities: list[Capability] | None = None


class Resolution1(BaseModel):
    width: int | None = Field(None, examples=[640])
    height: int | None = Field(None, examples=[640])


class CameraConfigSet(BaseModel):
    name: str | None = Field(
        None, description='Name of the camera', examples=['MuadDib_Camera_1']
    )
    trigger_scheme: TriggerScheme | None = Field(
        None, description='When the snapshot is taken'
    )
    resolution: Resolution1 | None = None
    rotation: int | None = Field(
        None, description='Current rotation of the output image', examples=[180]
    )
    focus: float | None = Field(
        None, description='Focus of the camera (0.0 - 1.0)', examples=[0.5]
    )
    exposure: float | None = Field(None, examples=[4.2])
    send_to_connect: bool | None = Field(None, examples=[True])


class Type1(Enum):
    PRINT_FILE = 'PRINT_FILE'
    FIRMWARE = 'FIRMWARE'
    FILE = 'FILE'
    FOLDER = 'FOLDER'


class GenericFileInfo(BaseModel):
    name: str = Field(..., description='Short Filename', examples=['SPICE~1.gco'])
    read_only: bool = Field(..., examples=[False])
    size: int | None = Field(
        None, description='Available for files only, not for folders', examples=[424242]
    )
    type: Type1 = Field(
        ...,
        description='File could be print file, firmware file, other (e.g. configuration) file, or folder',
    )
    m_timestamp: int = Field(
        ..., description='Timestamp in seconds', examples=[1648042843]
    )
    display_name: str | None = Field(
        None,
        description='Long Filename',
        examples=['Spice_Harvester_0.3mm_PLA_MK3S_12m.gcode'],
    )


class Refs(BaseModel):
    download: str | None = Field(None, examples=['/api/files/local/file.txt/raw'])


class FileInfo(GenericFileInfo):
    refs: Refs | None = None


class PrintFileRefs(BaseModel):
    download: str | None = Field(
        None,
        examples=[
            '/api/files/local/examples/Spice_Harvester_0.3mm_PLA_MK3S_42m.gcode/raw'
        ],
    )
    icon: str | None = Field(
        None,
        examples=[
            '/api/thumbnails/local/examples/Spice_Harvester_0.3mm_PLA_MK3S_42m.gcode.small.png'
        ],
    )
    thumbnail: str | None = Field(
        None,
        examples=[
            '/api/thumbnails/local/examples/Spice_Harvester_0.3mm_PLA_MK3S_42m.gcode.orig.png'
        ],
    )


class PrinterModel(Enum):
    MK3 = 'MK3'
    MK3S = 'MK3S'
    MINI = 'MINI'


class PrintFileMetadata(BaseModel):
    bed_temperature: int | None = Field(
        None, description='Degrees Celsius', examples=[60]
    )
    bed_temperature_per_tool: list[int] | None = Field(
        None, alias='bed_temperature per tool'
    )
    temperature: int | None = Field(
        None, description='Nozzle temperature, Degrees Celsius', examples=[215]
    )
    temperature_per_tool: list[int] | None = Field(None, alias='temperature per tool')
    brim_width: int | None = Field(None, description='Millimeters', examples=[0])
    estimated_printing_time__normal_mode_: str | None = Field(
        None, alias='estimated printing time (normal mode)', examples=['42m 42s']
    )
    estimated_print_time: int | None = Field(
        None, description='Seconds', examples=[25421]
    )
    faded_layers: int | None = Field(None, examples=[42])
    filament_cost: float | None = Field(None, alias='filament cost', examples=[0.57])
    filament_cost_per_tool: list[float] | None = Field(
        None, alias='filament cost per tool'
    )
    filament_used__cm3_: float | None = Field(
        None, alias='filament used [cm3]', examples=[12.42]
    )
    filament_used__cm3__per_tool: list[float] | None = Field(
        None, alias='filament used [cm3] per tool'
    )
    filament_used__g_: float | None = Field(
        None, alias='filament used [g]', examples=[15.42]
    )
    filament_used__g__per_tool: list[float] | None = Field(
        None, alias='filament used [g] per tool'
    )
    filament_used__mm_: float | None = Field(
        None, alias='filament used [mm]', examples=[5142.06]
    )
    filament_used__mm__per_tool: list[float] | None = Field(
        None, alias='filament used [mm] per tool'
    )
    filament_type: str | None = Field(None, examples=['PLA'])
    filament_type_per_tool: list[str] | None = Field(
        None, alias='filament_type per tool'
    )
    fill_density: str | None = Field(None, description='Percents', examples=['20%'])
    initial_exposure_time: int | None = Field(None, description='Seconds', examples=[5])
    layer_height: float | None = Field(None, description='Millimeters', examples=[0.3])
    material_name: str | None = Field(None, examples=['PLA Sandstorm Orange'])
    exposure_time: int | None = Field(None, description='Seconds', examples=[2])
    max_exposure_time: int | None = Field(None, description='Seconds', examples=[3])
    max_initial_exposure_time: int | None = Field(
        None, description='Seconds', examples=[3]
    )
    min_exposure_time: int | None = Field(None, description='Seconds', examples=[3])
    min_initial_exposure_time: int | None = Field(
        None, description='Seconds', examples=[1]
    )
    nozzle_diameter: float | None = Field(
        None, description='Millimeters', examples=[0.4]
    )
    nozzle_diameter_per_tool: list[float] | None = Field(
        None, alias='nozzle_diameter per tool'
    )
    normal_percent_present: bool | None = Field(None, examples=[True])
    normal_left_present: bool | None = Field(None, examples=[True])
    quiet_percent_present: bool | None = Field(None, examples=[True])
    quiet_left_present: bool | None = Field(None, examples=[True])
    layer_info_present: bool | None = Field(None, examples=[True])
    max_layer_z: float | None = Field(None, examples=[4.2])
    print_time: int | None = Field(None, description='Seconds', examples=[2542])
    printer_model: PrinterModel | None = None
    support_material: str | None = Field(None, examples=['PLA'])
    ironing: int | None = Field(None, examples=[0])
    required_resin_ml: float | None = Field(None, examples=[124.2])
    profile: str | None = Field(None, examples=['ultra_fast'])


class Refs1(BaseModel):
    download: str | None = Field(None, examples=['/api/files/local/firmware.hex/raw'])


class FirmwareFileInfoBasic(GenericFileInfo):
    refs: Refs1 | None = None


class Meta(BaseModel):
    version: str | None = Field(None, description='Firmware version in text format')
    printer_type: int | None = None
    printer_version: int | None = None


class FirmwareFileInfo(FirmwareFileInfoBasic):
    meta: Meta | None = None


class Info(BaseModel):
    mmu: bool | None = Field(None, examples=[False])
    name: str | None = Field(None, examples=['MuadDib'])
    location: str | None = Field(None, examples=['Arrakis'])
    farm_mode: bool | None = Field(None, examples=[False])
    nozzle_diameter: float | None = Field(None, examples=[0.4])
    min_extrusion_temp: int | None = Field(None, examples=[170])
    serial: str | None = Field(None, examples=['CZPX4720X004XC34242'])
    sd_ready: bool | None = Field(None, examples=[True])
    active_camera: bool | None = Field(None, examples=[True])
    hostname: str | None = Field(None, examples=['prusa-mk3.lan'])
    port: str | None = Field(None, examples=['/dev/tty'])
    network_error_chime: bool | None = Field(None, examples=[True])


class StatusJob(BaseModel):
    id: int | None = Field(None, examples=[420])
    progress: float | None = Field(None, description='Percents', examples=[42.0])
    time_remaining: int | None = Field(None, description='Seconds', examples=[520])
    time_printing: int | None = Field(None, description='Seconds', examples=[526])


class State(Enum):
    IDLE = 'IDLE'
    BUSY = 'BUSY'
    PRINTING = 'PRINTING'
    PAUSED = 'PAUSED'
    FINISHED = 'FINISHED'
    STOPPED = 'STOPPED'
    ERROR = 'ERROR'
    ATTENTION = 'ATTENTION'
    READY = 'READY'


class StatusPrinter1(BaseModel):
    ok: bool | None = Field(None, examples=[True])
    message: str | None = Field(None, examples=['OK'])


class StatusConnect(BaseModel):
    ok: bool | None = Field(None, examples=[True])
    message: str | None = Field(None, examples=['OK'])


class StatusPrinter(BaseModel):
    state: State
    temp_nozzle: float | None = Field(None, examples=[214.9])
    target_nozzle: float | None = Field(None, examples=[215.0])
    temp_bed: float | None = Field(None, examples=[59.5])
    target_bed: float | None = Field(None, examples=[60.0])
    axis_x: float | None = Field(
        None, description='Available only when printer is not moving', examples=[23.2]
    )
    axis_y: float | None = Field(
        None, description='Available only when printer is not moving', examples=[24.3]
    )
    axis_z: float | None = Field(None, examples=[0.5])
    flow: int | None = Field(None, examples=[95])
    speed: int | None = Field(None, examples=[100])
    fan_hotend: int | None = Field(None, examples=[420])
    fan_print: int | None = Field(None, examples=[420])
    status_printer: StatusPrinter1 | None = None
    status_connect: StatusConnect | None = None


class StatusTransfer(BaseModel):
    id: int = Field(..., examples=[72855542])
    time_transferring: int = Field(..., examples=[30])
    progress: float | None = Field(None, description='Percents', examples=[65.82])
    data_transferred: int | None = Field(None, examples=[123084800])


class StatusStorage(BaseModel):
    name: str = Field(..., examples=['LOCAL'])
    path: str = Field(..., examples=['/local'])
    read_only: bool = Field(..., examples=[False])
    free_space: int | None = Field(None, examples=[4202335])


class StatusCamera(BaseModel):
    id: str | None = Field(None, examples=['Ba1kmCbifTa8X'])


class PrusaLinkPackage(BaseModel):
    new_version: str | None = Field(
        None, description='Package version available for update', examples=['4.2-RC1']
    )


class Type2(Enum):
    NO_TRANSFER = 'NO_TRANSFER'
    FROM_WEB = 'FROM_WEB'
    FROM_CONNECT = 'FROM_CONNECT'
    FROM_PRINTER = 'FROM_PRINTER'
    FROM_SLICER = 'FROM_SLICER'
    FROM_CLIENT = 'FROM_CLIENT'
    TO_CONNECT = 'TO_CONNECT'
    TO_CLIENT = 'TO_CLIENT'


class Transfer(BaseModel):
    type: Type2 = Field(..., examples=['FROM_WEB'])
    display_name: str = Field(
        ...,
        description='Long Filename',
        examples=['Spice_Harvester_0.3mm_PLA_MK3S_12m.gcode'],
    )
    path: str = Field(..., examples=['/local'])
    url: str | None = Field(
        None,
        examples=[
            'https://files.printables.com/media/prints/42/gcodes/42_b42-242-442-8142c-424242/spice_harvester_0.3mm_pla_mk3s_12m.gcode'
        ],
    )
    size: str | None = Field(None, description='Bytes', examples=[239314])
    progress: float = Field(..., description='Percents', examples=[42.25])
    transferred: int = Field(
        ..., description='Transferred data in bytes', examples=[3276800]
    )
    time_remaining: int | None = Field(None, description='Seconds', examples=[61])
    time_transferring: int = Field(..., description='Seconds', examples=[42])
    to_print: bool = Field(
        ...,
        description='Whether or not print after finishing transfer (upload)',
        examples=[False],
    )


class JobSerialPrint(BaseModel):
    serial_print: bool | None = Field(
        False, description='Whether the printer is printing from the serial line'
    )


class File(BaseModel):
    name: str = Field(..., description='Short Filename', examples=['SPICE~1.gco'])
    display_name: str | None = Field(
        None,
        description='Long Filename',
        examples=['Spice_Harvester_0.3mm_PLA_MK3S_12m.gcode'],
    )
    path: str = Field(..., examples=['/local'])
    display_path: str | None = Field(None, examples=['/PrusaLink gcodes'])
    size: int | None = Field(None, description='Bytes', examples=[2393142])
    m_timestamp: int = Field(
        ..., description='Timestamp in seconds', examples=[1648042843]
    )
    meta: PrintFileMetadata | None = None
    refs: PrintFileRefs | None = None


class JobFilePrint(BaseModel):
    file: File | None = None


class State1(Enum):
    PRINTING = 'PRINTING'
    PAUSED = 'PAUSED'
    FINISHED = 'FINISHED'
    STOPPED = 'STOPPED'
    ERROR = 'ERROR'


class Job1(BaseModel):
    id: int = Field(..., examples=[420])
    state: State1
    progress: float = Field(..., description='Percents', examples=[42.0])
    time_remaining: int | None = Field(None, description='Seconds', examples=[520])
    time_printing: int = Field(..., description='Seconds', examples=[526])
    inaccurate_estimates: bool | None = Field(
        None,
        description='Whether the time estimates are accurate or inaccurate',
        examples=[False],
    )


class Job2(JobSerialPrint, Job1):
    pass


class Job3(JobFilePrint, Job1):
    pass


class Job(RootModel[Job2 | Job3]):
    root: Job2 | Job3


class Error(BaseModel):
    code: str | None = Field(
        None,
        description='Prusa error code. Must be string if we will have printer with code for example 04',
        examples=['10108'],
    )
    title: str = Field(
        ...,
        description='Prusa error text string with prefilled variable macros.',
        examples=['RESIN TOO LOW'],
    )
    text: str = Field(
        ...,
        description='Prusa error text string with prefilled variable macros.',
        examples=[
            'Measured resin volume 22.4 ml is lower than required for this print. Refill the tank and restart the print.'
        ],
    )
    url: str | None = Field(
        None,
        description='Link to the Prusa help page',
        examples=['https://help.prusa3d.com/en/10108/LHE3Q0I1'],
    )


class ResponsePlaintext(RootModel[str]):
    root: str = Field(
        'Project with same name has been already uploaded.',
        description='Prusa error message (raw_message)',
    )


class PrintFileInfoBasic(GenericFileInfo):
    refs: PrintFileRefs | None = None


class PrintFileInfo(PrintFileInfoBasic):
    meta: PrintFileMetadata | None = None


class FolderInfo(GenericFileInfo):
    children: (
        list[FileInfo | PrintFileInfoBasic | FirmwareFileInfoBasic | FolderInfo] | None
    ) = None


FolderInfo.model_rebuild()
